### ISSUE TITLE
MySQL fail to parser "Select @@XXX or SET NAMES utf8"

### ISSUE THREAD

**Issue by juaby** [andygrove/sqlparser-rs#156] opened 2020-04-03 06:07 UTC
RT:

SQL: 
```sql
"/* mysql-connector-java-5.1.48 ( Revision: 29734982609c32d3ab7e5cac2e6acee69ff6b4aa ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout"
```

**Comment by nickolay** [comment] 2020-04-03 13:32
https://github.com/andygrove/sqlparser-rs/blob/master/src/dialect/mysql.rs looks like it was explicitly coded to reject `@` and it has a link to the docs which doesn't mention @ either...

**Comment by nickolay** [comment] 2020-04-21 15:08
Hey. Sorry, but I'm going to close this, as I don't understand what the problem is from the description you've provided...

Please feel free to re-open if you care to elaborate, preferably with a minimal example and a link to the documentation.

**Closed by nickolay** 2020-04-21 15:08 UTC
